apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: chipp-issues
spec:
  connectionDraining:
    drainingTimeoutSec: 300
  timeoutSec: 86400
  healthCheck:
    requestPath: /api/health
    type: HTTP
    # Note: Do NOT specify port here - GKE will use the NodePort automatically
